/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import helpers.Img;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.History;
import page.formLobby;

/**
 *
 * @author TheNineInwKung
 */
public class HistoryItem extends javax.swing.JPanel {

    /**
     * Creates new form HistoryItem
     */
    public HistoryItem() {
        initComponents();
    }
    public HistoryItem(History history,int x,int y) {
        initComponents();
        try {
            this.imgshow.setIcon(new ImageIcon(Img.resize(Img.circle(new URL(history.getUser().getTemp())), 40, 40)));
        } catch (MalformedURLException ex) {
            Logger.getLogger(formLobby.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formLobby.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.name.setText(history.getUser().getName().substring(0,1).toUpperCase()+""+history.getUser().getName().substring(1).toLowerCase());
        this.score.setText(history.getStatus()+" "+history.getWin()+" : "+history.getLose());
        setBounds(x, y, 251, 50);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JPanel();
        imgshow = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        img.setBackground(new java.awt.Color(51, 51, 255));
        img.setOpaque(false);
        img.setLayout(new java.awt.CardLayout());
        img.add(imgshow, "card2");

        add(img);
        img.setBounds(5, 7, 40, 40);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name");
        add(name);
        name.setBounds(60, 0, 145, 26);

        score.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("Name");
        add(score);
        score.setBounds(60, 24, 145, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel img;
    private javax.swing.JLabel imgshow;
    private javax.swing.JLabel name;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
